version: 1
disable_existing_loggers: False

formatters:
  rich:
    format: '%(name)s: %(message)s'
    datefmt: '[%Y-%m-%d %H:%M:%S]'
  file:
    format: '[%(asctime)s] %(name)s(%(levelname)s): %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: rich.logging.RichHandler
    formatter: rich
    level: INFO
    rich_tracebacks: True
    markup: True
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: file
    level: INFO
    filename: logs/bot.log
    maxBytes: 10485760  # 10 MB
    backupCount: 10
    encoding: utf8

loggers:
  bot_logger:
    level: INFO
    handlers: [console, file]
    propagate: no

root:
  level: DEBUG
  handlers: [console, file]
